### ISSUE TITLE
Take into account outliers in TimeLogs

### ISSUE THREAD

**Issue by aparshin** [aparshin/isoxml-visualization#1]
Here is an example of handling outliers in the SDSD project: [range calculation](https://github.com/julianklose/sdsd/blob/master/website/src/main/java/de/sdsd/projekt/prototype/jsonrpc/MapEndpoint.java#L505) and [color selection](https://github.com/julianklose/sdsd/blob/master/website/src/main/resources/js/map-data.js#L386)

**Comment by aparshin** [comment]
@julianklose I've implemented in https://github.com/aparshin/isoxml-visualization/commit/56c25b48f0b0ab1ff35e37932aa252cd00714456 a slightly more conservative version of your algorithm from SDSD (Boxplot for unique values). Doesn't work for all the use cases, but should be useful sometimes. Thanks for the idea!

**Comment by julianklose** [comment]
Hi, is the update applied in the demo? Because this outlier handling doesn't seem to work yet:
![image](https://user-images.githubusercontent.com/48514372/157012640-1b1b3b0b-1e22-440f-b552-ecbc89bb6eb1.png)

**Comment by aparshin** [comment]
@julianklose Did you try to check the "Exclude outliers" checkbox on the left panel?

**Comment by julianklose** [comment]
Well... that's embarrassing xD I totally missed that. Sorry.
Yeah, it is better with that option set, but not quite perfect:
![image](https://user-images.githubusercontent.com/48514372/157057832-bc064ca9-8615-4a65-b1f9-cf1a130d4cd2.png)

**Comment by aparshin** [comment]
@julianklose Well, the current version of outlier removal is pretty conservative (it left more values than your implementation). But when I tried to relax it, it started to exclude some values, that seem valid to me. In this particular example, are you sure that the value 879 kg/ha (the max value) is an outlier?

I was thinking about allowing users to edit min/max values themselves, but I'm not sure that it's really needed.

**Comment by julianklose** [comment]
That depends on how you define an outlier I guess. I did not find the 879, but I found 792. As you can see it probably was at the start of the row when the machine was still standing but already activated the spreading. So if you define an outlier as one value that is completely out of range of all the other values, then it is ok. But the "normal" distribution is between 60 and 350 kg/ha. If you define an outlier as values that are out of the range of 99 percent of the other data points (excluding 0-values), then everything bigger than 350 and less than 60 should be an outlier. I'd rather actually see the whole color gradient than have to zoom in and find the few points that are red.
![image](https://user-images.githubusercontent.com/48514372/157072006-13f20913-9e76-4b63-ab09-43d3d2c0a4ed.png)
